name: Flama Final

on:
  pull_request:
    branches: [main]

permissions:
  contents: read

jobs:
  final:
    uses: maxbec/flama-delivery-platform/.github/workflows/reusable-final.yml@3915526f99c19231cbb08a43ce54e4a9f8f3a012
    with:
      base-sha: ${{ github.event.pull_request.base.sha }}
      head-sha: ${{ github.event.pull_request.head.sha }}
      platform-sha: 3915526f99c19231cbb08a43ce54e4a9f8f3a012
