name: Lint
on: [push, pull_request]
jobs:
    build:
        name: Add-on configuration
        runs-on: ubuntu-latest
        steps:
            - name: ⤵️ Check out code from GitHub
              uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
            - name: 🚀 Run Home Assistant Add-on Lint
              uses: frenck/action-addon-linter@ca747f8ea5ea80169eb39c62b10b0d6a517690c4 # v2.2
              with:
                  path: "./diyhue"
            - name: 🚀 Run Home Assistant Add-on Lint for BETA
              uses: frenck/action-addon-linter@ca747f8ea5ea80169eb39c62b10b0d6a517690c4 # v2.2
              with:
                  path: "./diyhue-beta"
