name: Lint
on: [push, pull_request]
jobs:
    build:
        name: Add-on configuration
        runs-on: ubuntu-latest
        steps:
            - name: ⤵️ Check out code from GitHub
              uses: actions/checkout@v2.3.4
            - name: 🚀 Run Home Assistant Add-on Lint
              uses: frenck/action-addon-linter@v2.9
              with:
                  path: "./diyhue"
            - name: 🚀 Run Home Assistant Add-on Lint for BETA
              uses: frenck/action-addon-linter@v2.9
              with:
                  path: "./diyhue-beta"
